workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    instance_type: linux

    environment:
      flutter: stable
      android_signing:
        - my_keystore
      groups:
        - google_play   # if you want to publish to Play Store
      vars:
        PACKAGE_NAME: "com.example.auto_revop"  # your app ID

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Increment Build Number
        script: |
          # Get latest Play Store build number if publishing, fallback to CM_BUILD_NUMBER
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
            UPDATED_BUILD_NUMBER=$CM_BUILD_NUMBER
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          echo "Updated build number: $UPDATED_BUILD_NUMBER"
          export BUILD_NUMBER=$UPDATED_BUILD_NUMBER

      - name: Build Android AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/app/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - autorevop@gmail.com  # update with your email
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
